kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
rules:
  - apiGroups:
    - cluster.x-k8s.io
    - cluster.x-k8s.io/v1beta1
    - infrastructure.cluster.x-k8s.io/v1beta1
    - infrastructure.cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    - machinepools
    - gcpmachinetemplates
    verbs:
    - get
    - list
    - update
    - watch