apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
spec:
  selector:
    matchLabels:
      app: cluster-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.28.0
        name: cluster-autoscaler
        command:
        - /cluster-autoscaler
        args:
        - --kubeconfig=/mnt/mycluster.kubeconfig
        - --clusterapi-cloud-config-authoritative
        - --cloud-provider=clusterapi
        - --node-group-auto-discovery=clusterapi:clusterName=mycluster
        volumeMounts:
        - name: kubeconfig-vol
          mountPath: /mnt
      serviceAccountName: cluster-autoscaler
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
